version: "3.9"
services:
  redis:
    image: redis:7
    container_name: redis-broker
    ports:
      - "6379:6379"

  jobmaster:
    build: ./jobmaster
    container_name: jobmaster-api
    ports:
      - "8010:8000"
    env_file:
      - ./jobmaster/.env      # Ruta a tu archivo .env para jobmaster
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # BACKEND_URL ya puede venir del .env, si quieres evitar duplicados puedes quitar esta línea
    depends_on:
      - redis

  worker1:
    build: ./worker
    container_name: celery-worker-1
    ports:
      - "8011:8000"
    env_file:
      - ./worker/.env         # Archivo .env para workers, si igual usan variables similares
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # BACKEND_URL también puede venir del .env
    depends_on:
      - redis

  worker2:
    build: ./worker
    container_name: celery-worker-2
    ports:
      - "8012:8000"
    env_file:
      - ./worker/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

networks:
  default:
    external:
      name: jobmaster-network
