version: "3.9"
services:
  redis:
    image: redis:7
    container_name: redis-broker
    ports:
      - "6379:6379"

  jobmaster:
    build: ./jobmaster
    container_name: jobmaster-api
    ports:
      - "8010:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  worker1:
    build: ./worker
    container_name: celery-worker-1
    ports:
      - "8011:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  worker2:
    build: ./worker
    container_name: celery-worker-2
    ports:
      - "8012:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

networks:
  default:
    external:
      name: jobmaster-network
